exports.games = [
    {name: 'Terraria'},
    {name: 'Dwarf Fortress'},
    {name: 'Stardew Valley'},
    {name: 'Valheim'},
    {name: 'Outer Wilds'},
    {name: 'Baldur\'s Gate 3'},
    {name: 'The Witcher 3: Wild Hunt'},
    {name: 'Street Fighter 6'},
    {name: 'Tekken 8'},
    {name: 'Hades'},
    {name: 'Elden Ring'},
    {name: 'Counter Strike 2'},
    {name: 'Valorant'},
    {name: 'Dota 2'},
    {name: 'League of Legends'},
    {name: 'Celeste'},
    {name: 'Risk of Rain 2'},
    {name: 'Alan Wake 2'},
    {name: 'Rocket League'},
    {name: 'Resident Evil 4'},
    {name: 'Animal Crossing: New Horizons'},
    {name: 'Cuphead'},
    {name: 'Monster Hunter: World'},
    {name: 'The Last of Us'},
    {name: 'Red Dead Redemption 2'},
    {name: 'Persona 5'},
];

exports.tags = [
    {name: 'Multiplayer',},
    {name: 'Singleplayer',},
    {name: 'Adventure',},
    {name: '2D',},
    {name: 'RPG',},
    {name: 'Colony Sim',},
    {name: 'Simulation',},
    {name: 'Strategy',},
    {name: 'Farming Sim',},
    {name: 'Casual',},
    {name: 'PVP',},
    {name: 'Horror',},
    {name: 'Rogue-like',},
    {name: 'Indie',},
    {name: 'Survival',},
    {name: 'Co-op',},
    {name: 'Open World',},
    {name: 'Competitive',},
    {name: 'Exploration',},
    {name: 'Puzzle',},
    {name: 'Story Rich',},
    {name: 'Sandbox',},
    {name: 'Pixel Graphics',},
    {name: 'FPS',},
    {name: 'Fighting',},
    {name: 'MOBA',},
    {name: 'Difficult',},
    {name: 'Platformer',},
    {name: 'Mystery',},
];