exports.games = [
    {appid: 105600, name: 'Terraria', reviews: [], favoritedBy: [], tags: []},
    {appid: 975370, name: 'Dwarf Fortress', reviews: [], favoritedBy: [], tags: []},
    {appid: 413150, name: 'Stardew Valley', reviews: [], favoritedBy: [], tags: []},
    {appid: 892970, name: 'Valheim', reviews: [], favoritedBy: [], tags: []},
    {appid: 753640, name: 'Outer Wilds', reviews: [], favoritedBy: [], tags: []},
    {appid: 1454400, name: 'Cookie Clicker', reviews: [], favoritedBy: [], tags: []},
];

exports.tags = [
    {name: 'Multiplayer', games: [],},
    {name: 'Singleplayer', games: [],},
    {name: 'Adventure', games: [],},
    {name: '2D', games: [],},
    {name: 'RPG', games: [],},
    {name: 'Colony Sim', games: [],},
    {name: 'Simulation', games: [],},
    {name: 'Strategy', games: [],},
    {name: 'Farming Sim', games: [],},
    {name: 'Casual', games: [],},
    {name: 'Space', games: [],},
    {name: 'Mystery', games: [],},
    {name: 'Idle', games: [],},
    {name: 'Clicker', games: [],},
    {name: 'Indie', games: [],},
    {name: 'Survival', games: [],},
    {name: 'Co-op', games: [],},
    {name: 'Open World', games: [],},
    {name: 'Competitive', games: [],},
    {name: 'Exploration', games: [],},
    {name: 'Puzzle', games: [],},
    {name: 'Story Rich', games: [],},
    {name: 'Sandbox', games: [],},
    {name: 'Pixel Graphics', games: [],},
];