exports.games = [
    {appid: 105600, name: 'Terraria', favoritedBy: [], tags: []},
    {appid: 975370, name: 'Dwarf Fortress', favoritedBy: [], tags: []},
    {appid: 413150, name: 'Stardew Valley', favoritedBy: [], tags: []},
    {appid: 892970, name: 'Valheim', favoritedBy: [], tags: []},
    {appid: 753640, name: 'Outer Wilds', favoritedBy: [], tags: []},
    {appid: 1454400, name: 'Cookie Clicker', favoritedBy: [], tags: []},
];

exports.tags = [
    {name: 'Multiplayer',},
    {name: 'Singleplayer',},
    {name: 'Adventure',},
    {name: '2D',},
    {name: 'RPG',},
    {name: 'Colony Sim',},
    {name: 'Simulation',},
    {name: 'Strategy',},
    {name: 'Farming Sim',},
    {name: 'Casual',},
    {name: 'Space',},
    {name: 'Mystery',},
    {name: 'Idle',},
    {name: 'Clicker',},
    {name: 'Indie',},
    {name: 'Survival',},
    {name: 'Co-op',},
    {name: 'Open World',},
    {name: 'Competitive',},
    {name: 'Exploration',},
    {name: 'Puzzle',},
    {name: 'Story Rich',},
    {name: 'Sandbox',},
    {name: 'Pixel Graphics',},
];